# NAME: Default

payload:
  - DOMAIN-SUFFIX,notion.so
  - DOMAIN-SUFFIX,www.notion.so
  - DOMAIN-KEYWORD,notion

  - DOMAIN-SUFFIX,v2ex.com
  - DOMAIN-SUFFIX,www.v2ex.com
  - DOMAIN-SUFFIX,imagility.io
  - DOMAIN-SUFFIX,bing.com
  - DOMAIN-SUFFIX,you.com
  - DOMAIN-SUFFIX,www.you.com
  - DOMAIN-SUFFIX,www.right.com.cn
  - DOMAIN-SUFFIX,www.52pojie.cn
  - DOMAIN-SUFFIX,challenges.cloudflare.com
  - DOMAIN-SUFFIX,cloudflare-challenges.com
  - DOMAIN-SUFFIX,turnstile.cloudflare.com
  - DOMAIN-SUFFIX,fpnpmcdn.net
  - DOMAIN-SUFFIX,api.fpjs.io
  - DOMAIN-SUFFIX,0ait.com
  - DOMAIN-SUFFIX,agentrouter.org
  - DOMAIN-SUFFIX,game.placegame.cn
#  - DOMAIN-KEYWORD,telegram
#  - IP-CIDR,109.239.140.0/24
#  - IP-CIDR,149.154.160.0/20
#  - PROCESS-NAME,nekox.messenger
#  - PROCESS-NAME,org.telegram.messenger
#  - PROCESS-NAME,telegram.exe
